# Generated by Django 5.2.6 on 2025-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identity', models.CharField(max_length=20)),
                ('professional_position', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=20)),
                ('archetype', models.CharField(max_length=20)),
            ],
        ),
    ]
