# Generated by Django 5.2.6 on 2025-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REU_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
