# Generated by Django 5.2.6 on 2025-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REU_Project', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
