# Generated by Django 5.2.6 on 2025-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REU_Project', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pdf', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
