# Generated by Django 5.2.6 on 2025-11-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REU_Project', '0004_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
